### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by schaitanya** [omnomagonz/Javascript#1]
Housekeeping
- [x] Cleanup code (move files to their respective dirs. css/js/templates)

User Management
- [x] Account creation
- [x] Log in
- [x] Account Settings
- [x] List of authored posts
- [x] List of comments

**Comment by omnomagonz** [comment]
Completed these high level tasks.  Creating new issues for granular features and fixes.
